FROM python:3.11-slim

RUN apt-get update && apt-get install -y default-jdk-headless && \
    rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/default-java

RUN pip install --no-cache-dir streamlit pyspark==3.5.3 delta-spark==3.0.0 pandas plotly

WORKDIR /app

CMD ["streamlit", "run", "app.py", "--server.address", "0.0.0.0"]